import fs from 'node:fs';

import { expect } from 'chai';
import { decode as decodePng } from 'fast-png';
import { after, describe, it } from 'mocha';

import { convertTexture } from '../../src/texture-convert/convert';
import { codecs, EXR_WASM } from '../../src/texture-convert/index';
import { textureOptions } from '../../src/texture-convert/options';

// generated by the monorepo's pipeline/jobs/texture-convert/tests/golden/make-golden.js from the real server chain
const DIR = 'test/fixtures/texture-convert/golden';
const golden = JSON.parse(fs.readFileSync(`${DIR}/golden.json`, 'utf8'));

// the worker's own codecs, with the wasm read from disk instead of streamed from the frontend
const disk = codecs((path) =>
    WebAssembly.compile(
        fs.readFileSync(
            path === EXR_WASM
                ? 'node_modules/exrs/node_modules/exrs-raw-wasm-bindgen/exrs_raw_wasm_bindgen_bg.wasm'
                : `src/wasm/${path}`
        )
    )
);

const LOSSY = ['jpeg', 'webp'];

// channel count as sharp's metadata reports it: jpeg SOF components, webp alpha flag
const channels = (buf: Uint8Array, format: string) => {
    if (format === 'png') {
        return decodePng(buf).channels;
    }
    if (format === 'jpeg') {
        for (let i = 2; i < buf.length; i += 2 + ((buf[i + 2] << 8) | buf[i + 3])) {
            if (buf[i + 1] === 0xc0 || buf[i + 1] === 0xc2) {
                return buf[i + 9];
            }
        }
    }
    const chunk = String.fromCharCode(...buf.subarray(12, 16));
    return chunk === 'VP8L' ? (buf[24] & 0x10 ? 4 : 3) : chunk === 'VP8X' && buf[20] & 0x10 ? 4 : 3;
};

const rgba = async (buf: ArrayBuffer, format: string) => {
    if (LOSSY.includes(format)) {
        return (await disk.decode(format, buf)).data;
    }
    const png = decodePng(new Uint8Array(buf));
    const n = png.width * png.height;
    const out = new Uint8Array(n * 4);
    for (let i = 0; i < n; i++) {
        const s = i * png.channels;
        out.set([png.data[s], png.data[s + 1], png.data[s + 2], png.channels === 4 ? png.data[s + 3] : 255], i * 4);
    }
    return out;
};

const stats: Record<string, { max: number; mean: number; rgb: number; bound: string }> = {};

describe('texture convert parity with the server', () => {
    after(() => {
        if (process.env.GOLDEN_STATS) {
            console.table(stats);
        }
    });

    for (const g of golden) {
        it(g.name, async () => {
            expect(textureOptions(g.meta, g.pow2), 'options').to.deep.equal(g.options);

            const input = fs.readFileSync(`${DIR}/${g.input}`);
            const res = await convertTexture(
                input.buffer.slice(input.byteOffset, input.byteOffset + input.byteLength),
                g.meta,
                g.options,
                disk
            );
            const file = new Uint8Array(res.file);
            const out = await rgba(res.file, g.output.format);
            const w = g.output.format === 'png' ? decodePng(file) : null;
            expect(channels(file, g.output.format), 'channels').to.equal(g.output.channels);
            expect(out.length, 'size').to.equal(g.output.width * g.output.height * 4);
            if (w) {
                expect([w.width, w.height], 'shape').to.deep.equal([g.output.width, g.output.height]);
            }

            const want = Buffer.from(g.raw, 'base64');
            let sum = 0;
            let rgb = 0;
            let max = 0;
            for (let i = 0; i < want.length; i++) {
                const d = Math.abs(want[i] - out[i]);
                sum += d;
                rgb += i % 4 === 3 ? 0 : d;
                max = Math.max(max, d);
            }

            // the bound is over every rgba sample, like the plan's test; rgb alone is reported alongside
            const mean = sum / want.length;

            // lossy encoders and resampling differ from sharp's; 16->8 may round by one; the rest is exact
            const bound =
                g.options.size || LOSSY.includes(g.output.format)
                    ? 'mean<=2'
                    : g.options.depthConvert
                      ? 'max<=1'
                      : 'max=0';
            stats[g.name] = { max, mean: +mean.toFixed(3), rgb: +((rgb * 4) / 3 / want.length).toFixed(3), bound };
            if (bound === 'mean<=2') {
                expect(mean, 'mean diff').to.be.at.most(2);
            } else if (bound === 'max<=1') {
                expect(max, 'max diff').to.be.at.most(1);
            } else {
                expect(max, 'max diff').to.equal(0);
            }
        });
    }
});
