window.DEFAULT_CULLING_MASK = 0xFFFFFFFF;
window.GEOMETRY_ONLY_CULLING_MASK = 1 | 2 | 4;
window.GIZMO_MASK = 8;

// Layer ids
window.LAYERID_WORLD = 0;
window.LAYERID_DEPTH = 1;
window.LAYERID_SKYBOX = 2;
window.LAYERID_IMMEDIATE = 3;
window.LAYERID_UI = 4;

// Layout groups
window.ORIENTATION_HORIZONTAL = 0;
window.ORIENTATION_VERTICAL = 1;
window.FITTING_NONE = 0;
window.FITTING_STRETCH = 1;
window.FITTING_SHRINK = 2;
window.FITTING_BOTH = 3;

// Buttons
window.BUTTON_TRANSITION_MODE_TINT = 0;
window.BUTTON_TRANSITION_MODE_SPRITE_CHANGE = 1;

// Scroll Views
window.SCROLL_MODE_CLAMP = 0;
window.SCROLL_MODE_BOUNCE = 1;
window.SCROLL_MODE_INFINITE = 2;

window.SCROLLBAR_VISIBILITY_SHOW_ALWAYS = 0;
window.SCROLLBAR_VISIBILITY_SHOW_WHEN_REQUIRED = 1;


window.CURVE_LINEAR = 0;
window.CURVE_SMOOTHSTEP = 1;
window.CURVE_CATMULL = 2;
window.CURVE_CARDINAL = 3;
window.CURVE_SPLINE = 4;
window.CURVE_STEP = 5;

// Script Loading Type
window.LOAD_SCRIPT_AS_ASSET = 0;
window.LOAD_SCRIPT_BEFORE_ENGINE = 1;
window.LOAD_SCRIPT_AFTER_ENGINE = 2;

// Anim system constants
window.ANIM_INTERRUPTION_NONE = 'NONE';
window.ANIM_INTERRUPTION_PREV = 'PREV_STATE';
window.ANIM_INTERRUPTION_NEXT = 'NEXT_STATE';
window.ANIM_INTERRUPTION_PREV_NEXT = 'PREV_STATE_NEXT_STATE';
window.ANIM_INTERRUPTION_NEXT_PREV = 'NEXT_STATE_PREV_STATE';

window.ANIM_GREATER_THAN = 'GREATER_THAN';
window.ANIM_LESS_THAN = 'LESS_THAN';
window.ANIM_GREATER_THAN_EQUAL_TO = 'GREATER_THAN_EQUAL_TO';
window.ANIM_LESS_THAN_EQUAL_TO = 'LESS_THAN_EQUAL_TO';
window.ANIM_EQUAL_TO = 'EQUAL_TO';
window.ANIM_NOT_EQUAL_TO = 'NOT_EQUAL_TO';

window.ANIM_PARAMETER_INTEGER = 'INTEGER';
window.ANIM_PARAMETER_FLOAT = 'FLOAT';
window.ANIM_PARAMETER_BOOLEAN = 'BOOLEAN';
window.ANIM_PARAMETER_TRIGGER = 'TRIGGER';

window.ANIM_STATE_START = 'START';
window.ANIM_STATE_END = 'END';

// VERSION CONTROL
window.MERGE_STATUS_AUTO_STARTED = 'merge_auto_started';
window.MERGE_STATUS_AUTO_ENDED = 'merge_auto_ended';
window.MERGE_STATUS_APPLY_STARTED = 'merge_apply_started';
window.MERGE_STATUS_APPLY_ENDED = 'merge_apply_ended';
window.MERGE_STATUS_READY_FOR_REVIEW = 'merge_ready_for_review';


// COPY-DELETE IN BACKEND
window.COPY_OR_DELETE_IN_BACKEND_LIMIT = 500;
